apiVersion: v1
kind: Pod
metadata:
 name: postgres-db-pod
 labels:
  name: postgres-db-pod
  app: demo-voting-app
spec:
 containers:
  - name: postgres-db
    image: rpostgres:9.4
    ports:
     - containerPort: 5432
