apiVersion: v1
kind: Service
metadata:
 name: redis-db-service
 labels:
  name: redis-db-service
  app: demo-voting-app
spec:
 ports:
  - port: 6379
    targetPort: 6379
 selector:
    name: redis-db-pod
    app: demo-voting-app
